---
layout:     post
title:      JavaScript async/await
subtitle:   ARTS Review 
date:       2018-07-09
author:     QA
header-img: img/post-bg-map.jpg
catalog: true
tags:
    - Review
    - ARTS
---

### 点评(Review)
原文主要介绍了async/await的精粹,陷阱和怎么使用.

async/await是ES7带来的新特性.它提供一种同步代码的方式来访问异步数据.

#### 精粹(Good Part)
1. 最大的好处是同步的编程风格.很显然比promise更容易理解.

    示例如下:

        // async/await
        async getBooksByAuthorWithAwait(authorId) {
            const books = await bookModel.fetchAll();
            return books.filter(b => b.authorId === authorId);
        }
        // promise
        getBooksByAuthorWithPromise(authorId) {
            return bookModel.fetchAll()
                .then(books => books.filter(b => b.authorId === authorId));
        }

2. 可读性增强,也得到原生浏览器的支持.

3. async和await仅仅是语法糖

#### 陷阱(Pitfalls)

1. 顺序请求

    例如:

        async getBooksAndAuthor(authorId) {
            const books = await bookModel.fetchAll();
            const author = await authorModel.fetch(authorId);
            return {
                author,
                books: books.filter(book => book.authorId === authorId),
            };
        }

- await bookModel.fetchAll() 会等待 fetchAll() 返回.
- 然后 await authorModel.fetch(authorId) 再会调用.

    代码:

        async getBooksAndAuthor(authorId) {
            const bookPromise = bookModel.fetchAll();
            const authorPromise = authorModel.fetch(authorId);
            const book = await bookPromise;
            const author = await authorPromise;
            return {
                author,
                books: books.filter(book => book.authorId === authorId),
            };
        }


### 异常处理(Error Handler)

1. 使用try catch

    有三种处理error的方式,1)直接处理,并返回正常值 2)抛出去 3)使用*return Promise.reject(error)*,不推荐
    好处是简单,可以将多个异常包在一起

2. 同时返回异常和正常结果
    例如:[err, user] = await to(UserModel.findById(1));

3. 使用.catch
    问题是混合promise和async,并且异常处理在正常处理之前.
    示例如下:

        // books === undefined if error happens,
        // since nothing returned in the catch statement
        let books = await bookModel.fetchAll()
        .catch((error) => { console.log(error); });

### 结论(Conclusion)
ES7带来的新特性,可读性强,方便调试.不过仅仅是语法糖,实际还是promise.

### 参考(Reference)
[JavaScript async/await: The Good Part, Pitfalls and How to Use](https://hackernoon.com/javascript-async-await-the-good-part-pitfalls-and-how-to-use-9b759ca21cda)